### ISSUE TITLE
Failed to load external entity

### ISSUE THREAD

**Issue by Awais-cb** [squidpickles/mpd-to-m3u8#1]
Hi i hope you are doing good
i am trying to implement mpd to to but every time i run this command
`xsltproc --stringparam run_id "segment" /var/www/html/file_conversion/out_heli/mpd_hls/mpd-to-hls.xsl /var/www/html/file_conversion/out_heli/output_heli_dash.mpd > /var/www/html/file_conversion/out_heli/hls_playlist/playlist.m3u8`
command line says
`failed to load external entity`
any solution to this i'd be very great-full for your help regarding this 
Thanks have a good day

**Comment by Awais-cb** [comment]
i am using ubuntu 16.10

**Comment by Awais-cb** [comment]
i am done with executing file but it says document is not a style sheet

**Comment by squidpickles** [comment]
I'm sorry, never got any notifications for this issue. Are you still having this problem? Do you have an example mpd file you could provide?
