### ISSUE TITLE
Question: Will this work with ClearKey encrypted media?

### ISSUE THREAD

**Issue by tiberiumihai** [squidpickles/mpd-to-m3u8#4]
Hi there,

Thanks for this awesome work!

I have a dash manifest.mpd generated using MP4Box from encrypted media (separate encrypted audio and encrypted video files) using ClearKey DRM.

Do you know if this will work to generate manifest.m3u8 so that the hls player will be able to decrypt ClearKey DRM?

Thanks!

**Comment by squidpickles** [comment]
Hi, I'm really not sure. I haven't looked at this stuff for a few years, and never worked with encrypted media. Give it a try! You might get lucky.

If you have examples of valid input and output files, I could probably get it working if it doesn't already.

**Comment by tiberiumihai** [comment]
There's no need. I've managed to generate both manifest.mpd and manifest.m3u8 using GPAC's dual filter introduced in 0.9.0.

**Comment by tiberiumihai** [comment]
But for what it's worth, I think you can achieve encrypted media hls manifest generation using plain ffmpeg by following this "guide": https://hlsbook.net/how-to-encrypt-hls-video-with-ffmpeg/

Haven't really tried it because I'm already using GPAC. But maybe someone else would be interested.
